export default [
  { name: "叛逆的鲁鲁修", rank: 10 },
  { name: "夏洛特", rank: 9 },
  { name: "数码宝贝", rank: 8 },
  { name: "死亡笔记", rank: 10 },
  { name: "火影忍者", rank: 9 },
  { name: "足球小将", rank: 8 },
  { name: "铁胆火车侠", rank: 10 },
  { name: "四驱兄弟", rank: 9 },
  { name: "哆啦A梦", rank: 8 },
  { name: "超能勇士", rank: 8 },
  { name: "中华小当家", rank: 10 },
  { name: "铁甲小宝", rank: 9 },
  { name: "光能使者", rank: 8 },
  { name: "CLANNAD", rank: 8 },
  { name: "犬夜叉", rank: 10 },
  { name: "海贼王", rank: 9 },
  { name: "摩托老鼠", rank: 8 },
];
