export default [
  {
    name: "圣女之歌",
    description: "爱与海的深情对唱",
    avatar: require("@/assets/images/games/1.jpg"),
    type: "端游",
    rank: 10,
  },
  {
    name: "生化奇兵无限",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/2.jpg"),
    type: "端游",
    rank: 9,
  },
  {
    name: "口袋妖怪红宝石",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/4.png"),
    type: "掌机",
    rank: 8,
  },
  {
    name: "明日方舟",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/3.jpg"),
    type: "手游",
    rank: 10,
  },
  {
    name: "三国杀",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/6.jpg"),
    type: "桌游",
    rank: 9,
  },
  {
    name: "三国志11",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/5.jpg"),
    type: "端游",
    rank: 8,
  },
  {
    name: "牧场物语",
    description: "矿石镇的伙伴们",
    avatar: require("@/assets/images/games/7.jpg"),
    type: "掌机",
    rank: 7,
  },
  {
    name: "逆转裁判",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/8.jpg"),
    type: "掌机",
    rank: 6,
  },
  {
    name: "王者荣耀",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/11.jpg"),
    type: "掌机",
    rank: 6,
  },
  {
    name: "FIFA07",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/9.jpg"),
    type: "掌机",
    rank: 6,
  },
  {
    name: "DotA",
    description: "为什么游戏是第九艺术",
    avatar: require("@/assets/images/games/10.jpg"),
    type: "掌机",
    rank: 6,
  },
];
