export default [
  {
    time: "2020",
    description: "",
    memos: [
      require("@/assets/images/memos/2020 (1).jpg"),
      require("@/assets/images/memos/2020 (2).jpg"),
      require("@/assets/images/memos/2020 (3).jpg"),
    ],
    keywords: ["疫情", "答辩", "爷爷"],
  },
  {
    time: "2019",
    keywords: ["VLOG", "秋招"],
    movies: [],
    memos: [
      require("@/assets/images/memos/2019 (4).jpg"),
      require("@/assets/images/memos/2019 (2).jpg"),
      require("@/assets/images/memos/2019 (3).jpg"),
    ],
    items: [
      "Adineo卫衣",
      "Adidas Original 外套",
      "Used鞋",
      "Genanx裤子",
      "Genanx卫衣",
      "NewBalance外套",
      "Adidas Ultrboost3.0",
      "Nike Gripp",
      "Taichi1.0",
      "貂蝉手办",
      "鲁鲁修手办",
    ],
    games: ["1生化奇兵无限", "隐形守护者7月"],
    books: [],
    places: [],
    people: ["云从小伙伴", "王浩文", "徐亚茹"],
  },
  {
    time: "2018",
    description: "",
    memos: [
      require("@/assets/images/memos/2018 (1).jpg"),
      require("@/assets/images/memos/2018 (2).jpg"),
      require("@/assets/images/memos/2018 (3).jpg"),
    ],
    keywords: ["LOVE", "SKETCH", "形象改变"],
    items: ["DELL G3"],
    people: ["郝慧", "王勤"],
  },
  {
    time: "2017",
    description: "支付宝全年消费8400",
    dead: ["余光中"],
    archives: ["和小朋友关系越来越好"],
    movies: [],
    books: [],
    places: [],
    memos: [
      require("@/assets/images/sketches/yqy (1).jpg"),
      require("@/assets/images/sketches/yqy (2).jpg"),
      require("@/assets/images/sketches/yqy (3).jpg"),
    ],
    people: ["关嘉伟", "赵静"],
  },
  {
    time: "2016",
    description: "和小朋友们玩的最多的一年，关系变得更好的一年",
    memos: [
      require("@/assets/images/sketches/yqy (4).jpg"),
      require("@/assets/images/sketches/yqy (5).jpg"),
      require("@/assets/images/sketches/yqy (6).jpg"),
    ],
    people: ["关嘉伟", "赵静"],
  },
];
