export default [
  {
    name: "2008",
    description: "",
    dead: [""],
    archives: [""],
    keywords: ["打砸抢", "汶川地震", "奥运开幕", "金融危机"],
    movies: [],
    books: [],
    places: ["昆明1月2月"],
    people: [],
  },
  {
    name: "2016",
    description: "和小朋友们玩的最多的一年，关系变得更好的一年",
    months: [
      {
        name: "JAN",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "FEB",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "MAR",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "APR",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "MAY",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "JUN",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "JUL",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技"],
      },
      {
        name: "AUG",
        items: [{ name: "" }],
        keywords: ["毕业", "重庆"],
      },
      {
        name: "SEP",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "OCT",
        items: [{ name: "" }],
        keywords: ["考研"],
      },
      {
        name: "NOV",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
      {
        name: "DEC",
        items: [{ name: "" }],
        keywords: ["毕业", "乔巴科技", "重庆", "考研"],
      },
    ],
    archives: ["和小朋友关系越来越好"],
    movies: [],
    books: [],
    places: [],
    people: ["关嘉伟", "赵静"],
  },
  {
    name: "2017",
    description: "支付宝全年消费8400",
    dead: ["余光中"],
    archives: ["和小朋友关系越来越好"],
    movies: [],
    books: [],
    places: [],
    people: ["关嘉伟", "赵静"],
  },
  {
    name: "2018",
    description: "",
    dead: [""],
    archives: [""],
    keywords: ["LOVE", "SKETCH", "潮流"],
    movies: [],
    books: [],
    places: [],
    people: ["郝慧", "王勤"],
  },
  {
    name: "2019",
    description: "",
    dead: [],
    archives: ["去了上海"],
    keywords: ["VLOG", "9月秋招"],
    movies: [],
    games: ["1生化奇兵无限", "隐形守护者7月"],
    books: [],
    places: [],
    people: ["云从小伙伴", "王浩文", "徐亚茹"],
  },
  {
    name: "2020",
    description: "",
    dead: [],
    archives: [],
    keywords: ["疫情", "答辩"],
    movies: [],
    books: [],
    places: [],
    people: ["王帅"],
  },
];
